classDiagram
    Vehiculo <|-- Carro
    Vehiculo <|-- Moto
    Vehiculo <|-- Camioneta

    class Carro{
      +numPuertas
    }
    class Moto{
      +cilindraje
    }
    class Camioneta{
      +capacidadCarga
    }
